
CREATE DATABASE EmpresaCJ302721X;
GO

USE EmpresaCJ302721X;
GO

CREATE TABLE FUNCIONARIOS (
	ID INT PRIMARY KEY,
	Nome VARCHAR(25) NOT NULL,
	Sexo VARCHAR(1) NULL,
	Admissao DATE NOT NULL,
	Salario DECIMAL (10, 2) NOT NULL
);
GO

SET DATEFORMAT DMY;
GO

INSERT INTO FUNCIONARIOS(
	ID,
	Nome,
	Sexo,
	Admissao,
	Salario)
VALUES (1, 'Maria da Silva', 'F','10/01/2018', 2500.00);
GO


INSERT INTO FUNCIONARIOS
	VALUES (2 , 'Pedro Pereira', 'M', '25/05/2015',990.00);
GO

--INSERT INTO FUNCIONARIOS 
--	VALUES (2 , 'Maria Cristina', 'F', '10/09/2015',1200.000) MESMA CHAVE PRIMARIA, VAI DAR ERRO
--GO


INSERT INTO FUNCIONARIOS VALUES (3, 'Maria Cristina','F', '10/09/2015',1200.000);
INSERT INTO FUNCIONARIOS VALUES (4, 'Antônio Carlos','M', '15/05/2015',990.00);
GO


INSERT INTO FUNCIONARIOS VALUES
	(5, 'Marcelo Augusto', 'M', '09/12/2017', 1900.00),
	(6, 'Pedro Silva', 'M', '15/11/2015', 1050.00),
	(7, 'Mônica da Silva', 'F', '12/10/2014', 3000.00),
	(8, 'Tiago Lima', 'M', '10/05/2016', 1350.50);
GO


SELECT *FROM FUNCIONARIOS;
GO

SELECT
	ID AS 'Código de Funcionário',
	Nome,
	Sexo,
	Salario AS 'Salário'
FROM FUNCIONARIOS;
GO

SELECT TOP 3
	ID,
	Nome
FROM FUNCIONARIOS;
GO



--FILTRO DE RESGISTROS COM WHERE --

SELECT * FROM FUNCIONARIOS
WHERE Sexo = 'M' And Salario >1000;
GO

SELECT *FROM FUNCIONARIOS
ORDER BY Nome;
GO

SELECT *FROM FUNCIONARIOS
ORDER BY Nome DESC;
GO

INSERT INTO FUNCIONARIOS VALUES
	(9, 'Maria Cristina','F', '21/09/2012',1700.000),
	(10, 'Maria Cristina','F', '10/10/2017',1400.000);
GO


SELECT * FROM FUNCIONARIOS
WHERE Salario <3000
ORDER BY Nome,
		Salario DESC;
GO

CREATE TABLE TESTE (
	ID INT,
	Nome CHAR (10)
);
GO

EXEC sp_columns TESTE;
GO

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ='TESTE';
GO

SELECT
	TABLE_CATALOG AS 'Banco de Dados',
	TABLE_NAME AS 'Tabela',
	ORDINAL_POSITION AS	'Posiçao',
	COLUMN_NAME AS 'Coluna',
	DATA_TYPE AS 'Tipo de Dados',
	COLLATION_NAME AS 'Idioma da Coluna',
	IS_NULLABLE AS 'Aceita Nulo?'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TESTE';
GO



